addons:
  apt:
    packages:
      - doxygen

script:
  - make test
  - make docs

deploy:
  provider: pages
  local-dir: api_docs/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
