name: doxygen docs

on:
  push:
    branches:
      - master


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ssciwr/doxygen-install@v1

      - name: Build docs using docker
        run: make docker-docs

      - name: Publish docs to gh-pages
        run: make docs-publish
