name: doxygen docs

on:
  push:
    branches:
      - master


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ssciwr/doxygen-install@v1

      - name: Build docs using docker
        run: make docs

      - name: Publish docs to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          make docs-publish
