name: doxygen docs

on:
  push:
    branches:
      - master
      - fix-of-the-fix


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ssciwr/doxygen-install@v1

      - name: Build docs using docker
        run: make docs

      - name: Publish docs to gh-pages
        run: make docs-publish
